# Generated by Django 5.0.1 on 2024-01-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_bannermodel_options_bannermodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
